---
- hosts: loadtester
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - vars/secrets.yml
  roles:
    - common
    - swap
    - unhangout-common
    - loadtester
  vars:
    # domain: set in hosts.cfg so we can iterate domains over many instances.
    main_user_name: "{{vault_main_user_name}}"
    ansible_become_pass: "{{vault_ansible_become_pass}}"
    main_user_salt: "{{vault_main_user_salt}}"
    main_user_authorized_keys: "{{vault_main_user_authorized_keys}}"
    admin_email: "{{vault_admin_email}}"
