---
- hosts: loadtester
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - vars/secrets.yml
    - vars/unhangout.yml
    - vars/loadtester.yml
  roles:
    - common
    - swap
    - unhangout-common
    - loadtester
