# Configuration for a local vagrant instance
---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    # Use ansible-vault to create vars/secrets.yml which defines all of the
    # variables in this file which are prefixed by 'vault_'.
    - vars/secrets.yml
    - vars/unhangout.yml
  roles:
    #- common
    #- swap
    - nginx
    #- monitored
    - letsencrypt-dummy
    #- letsencrypt-nginx
    #- letsencrypt
    - unhangout-common
    - unhangout
