---
- name: Install deps
  apt: pkg={{item}} state=installed
  with_items:
    - git
    - build-essential
    - nodejs
    - npm
    - redis-server
  tags: unhangout

- name: Link nodejs -> node
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link
  tags: unhangout

- name: Copy unhangout code
  git: repo={{unhangout_repo_url}} dest={{unhangout_repo_dir}} accept_hostkey=True version="{{unhangout_branch}}"
  register: register_unhangout_code
  notify: restart unhangout
  tags: unhangout

- name: Copy configuration file
  template: src=unhangout_conf.json dest={{unhangout_repo_dir}}/conf.json
  notify: restart unhangout
  tags: unhangout

- name: Copy load simulator conf file
  template: src=simulatorConf.js dest={{unhangout_repo_dir}}/simulatorConf.js
  tags: unhangout

- name: Install node deps
  npm: path={{unhangout_repo_dir}}
  notify:
   - restart unhangout
  tags: unhangout

- name: Permissions for node files
  action: treeperms
  args:
    paths:
      - path: "{{unhangout_repo_dir}}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "u=rwX,g=rX,o=rX"
      - path: "{{unhangout_repo_dir}}/node_modules"
        state: "directory"
      - path: "{{unhangout_repo_dir}}/logs"
        state: "directory"
        owner: "www-data"
        group: "root"
        mode: "u=rwX,g=rwX,o=rX"
      - path: "{{unhangout_repo_dir}}/public/logs"
        state: "directory"
        owner: "www-data"
        group: "root"
        mode: "u=rwX,g=rwX,o=rX"
      - path: "{{unhangout_repo_dir}}/public/logs/chat"
        state: "directory"
        owner: "www-data"
        group: "root"
        mode: "u=rwX,g=rwX,o=rX"
      - path: "{{unhangout_repo_dir}}/node_modules/googleapis/.cache"
        state: "directory"
        owner: "www-data"
        group: "root"
        mode: "u=rwX,g=rwX,o=rX"
  tags: unhangout
